extern crate linux_embedded_hal as hal;
#[macro_use]
extern crate nb;
extern crate apds9960;

use std::collections::{Vec, HashMap};

use hal::I2cdev;
use apds9960::Apds9960;

use rppal::gpio::{Gpio, InputPin};
// use std::sync::{Arc, Mutex};

mod sensor_control {

    enum Gesture {
        Up,
        Down,
        Left,
        Right    
    };

    type GesturesCollection = HashMap<&str, Vec<Gesture>>;

    struct SensorControl {
        fn setup(&self) -> Result<(), ()>;
        fn process_gesture(&self) -> Result<(), ()>;
    }

    impl SensorControl {
        pub fn new() -> Self {
            // TODO check this
            SensorControl {}
        }

        pub fn setup(&self, &is_interrupt_triggered : bool) -> Option<()> {
            // TODO Flow
            /*
            1. Initialize the APDS9960 sensor.
            2. Enable proximity, and gesture detection.
            3. Setup proximity interrupt and Enable interrupt threshold. max 255, min something more than 0. TODO
            4. Set threshold which will set GMODE to 1.
            5. setup gpio for interrupt p
            */ 
        }

        pub fn process_gesture(&self, &gestures_to_detect : GesturesCollection) -> Result<(), ()> {
            // This assumes gmode is already 1.

            // TODO return type must match
            
            let mut data = [0; 6*4];    // TODO amount may not be correct. Repeated read?
            block!(sensor.read_gesture_data(&mut data)).unwrap();
            // TODO not sure how data will look like. Test


            
            Ok(())
        }

        pub fn test() {
            // TODO below generated by Gemini
            // let mut sensor = APDS9960::new()?;
            // sensor.enable_proximity()?;
            // sensor.enable_color()?;
            // sensor.enable_gesture()?;

            // loop {
            //     if let Some(proximity) = sensor.read_proximity()? {
            //         println!("Proximity: {}", proximity);
            //     }
            //     if let Some(color) = sensor.read_color()? {
            //         println!("Color: {:?}", color);
            //     }
            //     if let Some(gesture) = sensor.read_gesture()? {
            //         println!("Gesture: {:?}", gesture);
            //     }
            // }
        }
    }
}

